package br.com.clinica;

import br.com.clinica.model.Usuario;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;

public class MainPainel {
    // Componentes
    private JPanel mainPainel;
    private JButton sairButton;
    private JButton cadastrarNovoPacienteButton;
    private JButton adminButton;
    private JButton prontuarioEButton;
    private JButton marcacoesButton;
    private JLabel labelBoasVindas;
    private JLabel labelHora;
    private JLabel labelDia;
    private JLabel labelTemperatura;

    private final Usuario usuarioLogado;

    public MainPainel(Usuario usuario) {
        this.usuarioLogado = usuario;


        configurarLabelsDinamicos();
        configurarEventos();
    }

    public JPanel getMainPainel() {
        return mainPainel;
    }

    private void configurarLabelsDinamicos() {
        // Label de Boas-vindas com o nome do usuario
        labelBoasVindas.setText("Olá, " + usuarioLogado.getNome());

        // Configura data e hora
        atualizarData();
        Timer timerHora = new Timer(1000, e -> atualizarHora());
        timerHora.start();

        // Função para buscar a temperatura (Com API)
        buscarTemperatura();
    }


    private void atualizarData() {
        LocalDate hoje = LocalDate.now();
        Locale localeBrasil = new Locale("pt", "BR");
        String diaDaSemana = hoje.getDayOfWeek().getDisplayName(TextStyle.FULL, localeBrasil);
        DateTimeFormatter formatadorData = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy", localeBrasil);
        labelDia.setText(diaDaSemana + ", " + hoje.format(formatadorData));
    }

    private void atualizarHora() {
        DateTimeFormatter formatadorHora = DateTimeFormatter.ofPattern("HH:mm:ss");
        labelHora.setText("Hora: " + LocalDateTime.now().format(formatadorHora));
    }

    private void buscarTemperatura() {
        SwingWorker<String, Void> worker = new SwingWorker<>() {
            @Override
            protected String doInBackground() throws Exception {
                URL url = new URL("https://wttr.in/Feira%20de%20Santana?format=%t");
                HttpURLConnection con = (HttpURLConnection) url.openConnection();
                con.setRequestMethod("GET");
                try (BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()))) {
                    return in.readLine();
                }
            }

            @Override
            protected void done() {
                try {
                    String temperatura = get();
                    labelTemperatura.setText(temperatura != null && !temperatura.isEmpty() ? "Temperatura: " + temperatura : "Temperatura: N/A");
                } catch (Exception e) {
                    labelTemperatura.setText("Temperatura: Erro");
                }
            }
        };
        worker.execute();
    }

    private void configurarEventos() {
        sairButton.addActionListener(e -> {
            int resposta = JOptionPane.showConfirmDialog(mainPainel.getTopLevelAncestor(), "Você realmente deseja sair?", "Confirmar Saída", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        });

        cadastrarNovoPacienteButton.addActionListener(e -> {
            JOptionPane.showMessageDialog(mainPainel.getTopLevelAncestor(), "Tela de cadastro em breve!");
            // Futuramente: new CadastroPacienteForm();
        });

        adminButton.addActionListener(e -> {
            JOptionPane.showMessageDialog(mainPainel.getTopLevelAncestor(), "Tela de admin em breve!");
            // Futuramente: new AdminForm();
        });
        prontuarioEButton.addActionListener(e -> {
            JOptionPane.showMessageDialog(mainPainel.getTopLevelAncestor(), "Tela de prontuários em breve!");
            // Futuramente: new ProntuarioForm();
        });
        marcacoesButton.addActionListener(e -> {
            JOptionPane.showMessageDialog(mainPainel.getTopLevelAncestor(), "Tela de marcações em breve!");
            // Futuramente: new MarcacoesForm();
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPainel = new JPanel();
        mainPainel.setLayout(new GridLayoutManager(10, 11, new Insets(0, 0, 0, 0), -1, -1));
        mainPainel.setBackground(new Color(-1576449));
        final Spacer spacer1 = new Spacer();
        mainPainel.add(spacer1, new GridConstraints(1, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        sairButton = new JButton();
        sairButton.setText("Sair");
        mainPainel.add(sairButton, new GridConstraints(0, 9, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cadastrarNovoPacienteButton = new JButton();
        cadastrarNovoPacienteButton.setText("Cadastrar Novo Paciente");
        mainPainel.add(cadastrarNovoPacienteButton, new GridConstraints(0, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        adminButton = new JButton();
        adminButton.setText("Admin");
        mainPainel.add(adminButton, new GridConstraints(0, 8, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        prontuarioEButton = new JButton();
        prontuarioEButton.setText("Prontuário E.");
        mainPainel.add(prontuarioEButton, new GridConstraints(0, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPainel.add(spacer2, new GridConstraints(2, 0, 1, 11, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        mainPainel.add(spacer3, new GridConstraints(3, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        labelBoasVindas = new JLabel();
        labelBoasVindas.setForeground(new Color(-16777216));
        labelBoasVindas.setText("Olá, ");
        mainPainel.add(labelBoasVindas, new GridConstraints(8, 0, 2, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelHora = new JLabel();
        labelHora.setForeground(new Color(-16777216));
        labelHora.setText("Hora:");
        mainPainel.add(labelHora, new GridConstraints(4, 8, 1, 3, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelDia = new JLabel();
        labelDia.setForeground(new Color(-16777216));
        labelDia.setText("Dia:");
        mainPainel.add(labelDia, new GridConstraints(5, 9, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        mainPainel.add(spacer4, new GridConstraints(7, 10, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        labelTemperatura = new JLabel();
        labelTemperatura.setForeground(new Color(-16777216));
        labelTemperatura.setText("Temperatura:");
        mainPainel.add(labelTemperatura, new GridConstraints(6, 9, 1, 2, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        mainPainel.add(spacer5, new GridConstraints(7, 9, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        marcacoesButton = new JButton();
        marcacoesButton.setText("Marcações");
        mainPainel.add(marcacoesButton, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer6 = new Spacer();
        mainPainel.add(spacer6, new GridConstraints(7, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPainel;
    }

}